Controllers/OfferListController.cs
using IdentityDotNet.Data;
using IdentityDotNet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IdentityDotNet.Controllers
{
    public class OfferListController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OfferListController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexOffer()
        {
            return View(await _context.offerList.ToArrayAsync());
        }

        public IActionResult CreateOffer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOfferAsync(OfferList model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _context.offerList.AddAsync(model);
                    _context.SaveChanges();

                    return RedirectToAction("IndexOffer");
                }
                return View(model);

            }
            catch (Exception ex)
            {
                return NotFound(ex);
            }
        }

        public async Task<IActionResult> Edit (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await _context.offerList.FindAsync(id);

            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(OfferList model)
        {
            if (ModelState.IsValid)
            {
                _context.offerList.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("IndexOffer");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var result = await _context.offerList.FindAsync(id);

                if (result == null)
                {
                    return NotFound();
                }

                _context.offerList.Remove(result);
                await _context.SaveChangesAsync();

                return RedirectToAction("IndexOffer");
            }catch (Exception ex)
            {
                return View(ex);
            }
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityDotNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IdentityDotNet.styles.css" asp-append-version="true" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/โลโก้ทีมฉุกเฉิน.jpg" width="50" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold fs-5" asp-area="" asp-controller="Home" asp-action="Index">รับแจ้งเหตุ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold fs-5" asp-area="" asp-controller="OfferList" asp-action="IndexOffer">งานเสนอต่างๆ</a>
                        </li>
                    </ul>
                    <partial name="_LayoutPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2567 - แผนกเฝ้าระวังและตอบโต้เหตุฉุกเฉิน
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<AppUser> signInManager

<ul class="navbar-nav">
    @if (signInManager.IsSignedIn(User))
    {
        <li class="d-flex align-items-center">
            <a class="nav-link">
                    @User.Identity!.Name!
            </a>
            <a class="p-2" asp-action="Logout" asp-controller="Account">
                <img src="/user-logout.png" width="30"/>
            </a>
        </li>     
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark btn btn-dark text-white" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
        </li>
        
    }
</ul>